

CONFIG_ZMK_RTT_LOGGING=y


CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=y
# CONFIG_ZMK_USB_LOGGING=y
CONFIG_I2C=n
# CONFIG_SPI=n
CONFIG_LOG_BUFFER_SIZE=512

CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_USB_DEVICE_LOG_LEVEL_INF=n

# west build -b cornixqf \
#   -S zmk-usb-logging \
#   -- -DSHIELD=cornixqf_right
# 增加主栈大小
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_IDLE_STACK_SIZE=1024

# 增加中断栈
CONFIG_ISR_STACK_SIZE=4096

# 系统栈
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096