

CONFIG_ZMK_RTT_LOGGING=n

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_ZMK_USB_LOGGING=y
CONFIG_I2C=n
# CONFIG_SPI=n
CONFIG_LOG_BUFFER_SIZE=512

CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_USB_DEVICE_LOG_LEVEL_INF=n


