
CONFIG_CLOCK_CONTROL_NRF=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

CONFIG_LOG_MAX_LEVEL=4
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_LOG=n
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_ZMK_RTT_LOGGING=n
CONFIG_LOG_MODE_DEFERRED=y

CONFIG_USE_DT_CODE_PARTITION=y
CONFIG_BT_PERIPHERAL=y

CONFIG_MPU_ALLOW_FLASH_WRITE=y
CONFIG_NVS=y
CONFIG_BT_SETTINGS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y


CONFIG_ZMK_USB=y

CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=n
CONFIG_BT_DEVICE_NAME="Right-BLE"
CONFIG_USB_DEVICE_PRODUCT="WCorne-right"
CONFIG_USB_HID_DEVICE_COUNT=2

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n  
CONFIG_ZMK_SPLIT_PERIPHERAL_HID_INDICATORS=y
# CONFIG_PERIPHERAL_QF=y
CONFIG_ZMK_SPLIT_BLE=y  


CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORTING_FETCH_MODE_STATE_OF_CHARGE=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# CONFIG_ZMK_BATTERY_REPORT_INTERVAL=10
CONFIG_BT_BAS=y



# 蓝牙连接安全设置取消  by TY @20260910
CONFIG_BT_SMP_ENFORCE_MITM=n
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_BT_CTLR_PHY_2M=n


# 空闲自动关闭(推荐省电) by TY @20260910
# 左右手RGB自动关闭使用自定义的idle事件处理 by TY @20260914
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_IDLE_TIMEOUT=10000
# CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y

# Enable RGB underglow
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW=y

# 开机自动开启
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MIN=4


# 打开ZMK Mousekey支持 by TY @20260915
CONFIG_ZMK_POINTING=y

#临时清除所有设置
#CONFIG_ZMK_SETTINGS_RESET_ON_START=y