
CONFIG_SPI=y
CONFIG_SPI_NRFX=y
CONFIG_LOG_MAX_LEVEL=3
CONFIG_LOG_MODE_MINIMAL=n
CONFIG_ZMK_RTT_LOGGING=n
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_ZMK_LOG_LEVEL_DBG=n
CONFIG_PM_DEVICE=y
CONFIG_SENSOR_LOG_LEVEL_INF=n
CONFIG_LOG_MODE_DEFERRED=y


CONFIG_BT_DEVICE_NAME="P42-BLE1"
CONFIG_USB_DEVICE_PRODUCT="P42-zmk"
CONFIG_EEPROM_WEAR_LEVELING=y
CONFIG_USB_HID_DEVICE_COUNT=2

CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=1

CONFIG_ZMK_QF_595=y
CONFIG_BT_ID_MAX=4
CONFIG_BT_MAX_CONN=6

CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW=y

# 开机自动开启
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1
# 空闲自动关闭(推荐省电)
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=50

CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_LED_STRIP=y
CONFIG_USB_DEVICE_REMOTE_WAKEUP=y

# CONFIG_MPSL=y
# CONFIG_ESB=y
# CONFIG_MPSL_TIMESLOT=y
# CONFIG_NRFXLIB_ESB=y
# CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1

# CONFIG_BT_LL_SW_SPLIT=n
# CONFIG_BT_CTLR=y
# CONFIG_MPSL_TIMESLOT=y
# CONFIG_HAS_NORDIC_MDK=y

CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=n
CONFIG_LOG_OUTPUT_FORMAT_TIME_TIMESTAMP=n